In [1]:
print("Hello World!")

Hello World!


In [2]:
a = 3
b = 'A'
c = "test"
d = 5 + 9 - 3 * 7 / 12 ** 3

print(a, b, c, d)
s = f"Değerler a: {a}, b: {b}"
print(f"s'nin değeri: {s}")

3 A test 13.987847222222221
s'nin değeri: Değerler a: 3, b: A


In [3]:
my_list = [1, 2, "hey", 'x']
print(my_list)

my_list.append("Test")
print(my_list)

print(my_list[2])

print(len(my_list))

[1, 2, 'hey', 'x']
[1, 2, 'hey', 'x', 'Test']
hey
5


In [ ]:
kelimeler = "Hey ho lets go".split()
print(kelimeler)

In [4]:
for i in range(4):
    print(i)

0
1
2
3


In [5]:
for el in my_list:
    print(el)

1
2
hey
x
Test


In [6]:
for i, el in enumerate(my_list):
    print(i, el)

0 1
1 2
2 hey
3 x
4 Test


In [7]:
x = [a**2 for a in range(9)] # list comprehension
print(x)

[0, 1, 4, 9, 16, 25, 36, 49, 64]


In [8]:
even_x = [el for el in x if el % 2 == 0 ]
print(even_x)

[0, 4, 16, 36, 64]


In [9]:
even_x[2]

16

In [ ]:
even_x[2:]

In [ ]:
even_x[-1]

In [ ]:
even_x[:3]

In [ ]:
even_x[2:4]

In [ ]:
even_x[-2:]

In [ ]:
def kare_topla(a, b):
    a2 = a ** 2
    b2 = b ** 2
    return a2 + b2

kt = kare_topla(3, 4)
print(kt)

In [10]:
import re

def tekrarsiz_kelimelere_ayir(s):
    kelimeler = re.split(" ", s)
    return set(kelimeler)

print(tekrarsiz_kelimelere_ayir("üç kere üç dokuz eder"))

{'eder', 'kere', 'üç', 'dokuz'}


In [ ]:
my_dictionary = {} # dictionary
my_dictionary["ali"] = 3
my_dictionary["veli"] = 5
my_dictionary["ayse"] = [1, 2, 3]

print(my_dictionary)

In [ ]:
for k, v in my_dictionary.items():
    print(k, v)

In [ ]:
for k in my_dictionary:
    print(k, my_dictionary[k])

In [ ]:
"ali" in my_dictionary

In [ ]:
"xyz" in my_dictionary

In [11]:
kelimeler = ["sen", "sen", "ben", "sen", "ben", "gelme"]    #sınavda çıkacak soru bir cümlede kelimeler kaç kere tekrar ediyor
kelime_sayilari = {}

for kelime in kelimeler:
    if kelime in kelime_sayilari:
        kelime_sayilari[kelime] += 1
    else:
        kelime_sayilari[kelime] = 1

kelime_sayilari

{'sen': 3, 'ben': 2, 'gelme': 1}

In [12]:
l1, l2 = [1, 2, 3], [4, 5, 6]

In [24]:
toplam = 0
for i , z in zip(l1, l2):
    toplam += i * z
    print(toplam)

4
14
32


In [25]:
import numpy as np

In [26]:
l1 = np.array(l1)
l2 = np.array(l2)

l1 * l2

array([ 4, 10, 18])

In [27]:
np.dot(l1, l2)

32

In [28]:
np.max(l1)

3

In [29]:
l3 = np.array([1, 8, 9, 6, 3])
np.argmax(l3)

2

In [30]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3, 4))   #bu da birlerden oluşan matrix döner

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
l4 = np.array([x for x in range(15)])    #belirli sayıya kadar array yazabilmek için
l4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
l4.reshape((3, 5))   #düz olanı matrix yapıyor

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
l4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
mat = l4.reshape((5, -1))    #5 satır ve kaç elemandan oluşuyorsa o kdr sütun ekle demektir -1
print(mat)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
mat.shape   #kaç sütun ve satırdan oluşuyor

(5, 3)

In [46]:
!wget https://raw.githubusercontent.com/ihpar/ddi/main/cities.csv

--2024-11-23 07:29:01--  https://raw.githubusercontent.com/ihpar/ddi/main/cities.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-23 07:29:01 ERROR 404: Not Found.



In [42]:
import pandas as pd

In [50]:
df = pd.read_csv("cities.csv")

In [51]:
df.head()  # ilk beş satırını döndürür

In [ ]:
df.tail()  # son 5 satırını döndürür

In [ ]:
df.size  # eleman sayısı satır * sütun döndürür

In [ ]:
len(df)  # sadece satır sayısını döndürür sütun sayısını döndürmez

In [ ]:
df.shape # bir tuple (demet) döndürür: (satır_sayısı, sütun_sayısı)

In [ ]:
df.iloc[3]# sıfır tabanlı indeksleme ile 4.satır döner

In [ ]:
df.columns

In [ ]:
latD40 = df[df["LatD"] == 40]
"""
df["LatD"]: DataFrame'in "LatD" adlı sütununu seçer.
df["LatD"] == 40: Bu, "LatD" sütunundaki tüm değerlerin 40 olup olmadığını kontrol eder. Sonuç, True/False değerlerinden oluşan bir boolean seri olur.
df[...]: Koşulu karşılayan satırları seçmek için kullanılır.
latD40: Koşulu karşılayan satırların bulunduğu yeni bir DataFrame'dir.
"""

In [ ]:
latD40.head()

In [ ]:
df.hist("LatD")
"""
df.hist("LatD"), "LatD" sütunundaki verilerin dağılımını bir histogram ile görselleştirir.
Histogramın Çıktısı:
Yatay eksen (x-axis): "LatD" sütunundaki değer aralıklarını temsil eder.
Dikey eksen (y-axis): Her aralıkta kaç tane değer olduğunu gösterir (frekans).
"""